version: '2.1'

services:
  verdaccio:
    build: .
    container_name: verdaccio
    environment:
      - VERDACCIO_PORT
    ports:
      - $VERDACCIO_PORT:$VERDACCIO_PORT
    volumes:
      - ./docker-data/storage/verdaccio:/verdaccio/storage

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./docker-data/certbot/etc:/etc/letsencrypt
      - ./docker-data/certbot/var:/var/lib/letsencrypt
      - ./docker-data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-data/nginx/dhparam:/etc/ssl/certs
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 8443:8443
    depends_on:
      - verdaccio

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./certbot/etc:/etc/letsencrypt
#      - ./certbot/var:/var/lib/letsencrypt
#      - ./web/root:/var/www/html
#      - ./web/certbot:/var/www/certbot
#    depends_on:
#      - nginx
#    command: certonly --webroot --webroot-path=/var/www/html --register-unsafely-without-email --email korczis@gmail.com --agree-tos --no-eff-email --staging -d example.com
#    environment:
#      - VIRTUAL_HOST=korczis.com

volumes:
#  certbot:
#    driver: local
#  verdaccio-storage:
#    driver: local
#    driver_opts:
#      type: none
#      device: ./docker-data/storage/verdaccio
#      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ./data/nginx/dhparam/
      o: bind
