version: '2.1'

services:
  verdaccio:
    build: .
    container_name: verdaccio
#    environment:
#      - VERDACCIO_PORT
#    ports:
#      - $VERDACCIO_PORT:$VERDACCIO_PORT
    volumes:
      - ./docker-data/storage/verdaccio:/verdaccio/storage
      # - ./docker-data/storage/verdaccio/conf:/verdaccio/conf

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./docker-data/certbot/etc:/etc/letsencrypt
      - ./docker-data/certbot/var:/var/lib/letsencrypt
      - ./docker-data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-data/nginx/dhparam:/etc/ssl/certs
      - ./docker-data/storage/nginx/logs:/var/logs/nginx
    ports:
      - 80:80
      - 8080:8080
      - 4873:4873
    depends_on:
      - verdaccio

volumes:
  verdaccio:
    driver: local
    driver_opts:
      type: none
      device: ./docker-data/storage/verdaccio
      o: bind

